version: "3.5"
name: raopics
services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    command: [nginx, "-g", "daemon off;"]
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  api:
    image: meetqy/raopics-api
    ports:
      - 9600
    environment:
      LIBRARY: /library # volumes中的地址
    volumes:
      - /Users/qymeet/Pictures/test.library:/library # 本地挂载library地址

  rua:
    image: meetqy/raopics-rua
    ports:
      - 9601
    environment:
      - PORT=9601
