version: "3.5"
name: raopics
services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    command: [nginx, "-g", "daemon off;"]
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  api:
    tty: true
    build: ./
    environment:
      LIBRARY: /library # volumes中的地址
      PORT: 9600
    volumes:
      - /Users/qymeet/Pictures/rao.library/images:/library/images:ro # 本地挂载library地址
      - /Users/qymeet/Pictures/rao.library/metadata.json:/library/metadata.json:ro
      - /Users/qymeet/Pictures/rao.library/tags.json:/library/tags.json:ro
      - /Users/qymeet/Pictures/rao.library/raopics.db:/library/raopics.db

  rua:
    image: meetqy/raopics-rua
    environment:
      PORT: 9601
