version: "3.5"
name: raopics
services:
  api:
    image: meetqy/raopics-api
    ports:
      - "9600:9600"
    environment:
      LIBRARY: /library/test # volumes中的地址
    volumes:
      - /Users/qymeet/Pictures/test.library:/library/test # 本地挂载library地址

  rua:
    image: meetqy/raopics-rua
    ports:
      - "9601:9601"
    environment:
      API_HOST: http://localhost:9600 # api host
