name: 🐞 提交 Bug
description: 创建一个 bug 报告来帮助我们改进
title: "bug: "
labels: ["Bug"]
body:
  - type: dropdown
    id: systems
    attributes:
      label: 提供系统信息
      description: 选择你使用的系统
      options:
        - Windows
        - MacOS Arm
        - MacOS Inter
    validations:
      required: true
  - type: input
    attributes:
      label: 软件版本
      description: 右键点击状态栏图标 => 关于, 可以查看当前所使用的版本
    validations:
      required: true
  - type: input
    attributes:
      label: 系统版本
      description: 提供系统版本可以帮助我们更加快速定位问题
  - type: textarea
    attributes:
      label: 描述bug
      description: 清晰而简明地描述bug，以及在遇到bug时您期望发生的情况。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 复现步骤
      description: 描述如何复现您的bug。包括步骤、代码片段、复现仓库等。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 附加信息
      description: 在这里添加与bug相关的任何其他信息，如果适用，还可以包括屏幕截图。
