name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - meetqy
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"

  - type: dropdown
    id: platforms
    attributes:
      label: What platform are you seeing the problem on?
      multiple: true
      options:
        - Linux
        - Windows
        - MacOS
    validations:
      required: true
